### ISSUE TITLE
Reading errors when reading x and y from lockin

### ISSUE THREAD

**Issue by Chrede88** [folk-lab/IgorAcq#63]
I get reading errors when reading both x and y from the same lockin (only in async mode). No reading error is flagged, but it's totally an issue with the code and not a real signal.

**Comment by Chrede88** [comment]
Any ideas @nikhartman ?

**Comment by FolkLab** [comment]
No. I haven't tested that very extensively, though.

Are you good if you only measure x OR y?

**Comment by Chrede88** [comment]
Yep!

**Comment by Chrede88** [comment]
[dat2627.pdf](https://github.com/folk-lab/IgorAcq/files/1985444/dat2627.pdf)

**Comment by FolkLab** [comment]
I think it is mixing up the x and y responses. Does that make sense?

**Comment by nikhartman** [comment]
I think the way to fix this is to make sure that calls to the same instrument (check by looking at the `instrID` variable name) go into the same thread.

We can change the string variable `queryFunc` to be a semi-colon separated list, `queryFunc = "funcOne;funcTwo"` and pass the necessary waves to `sc_Worker`. The only part I don't know is how to pass multiple wave references to `sc_Worker`. That means instead of passing a single `datWave` to `sc_Worker` we will have to pass a wave of wave references (see docs for `make`, requires `\WAVE` flag).

Can you hack your way around it for now and I'll make these changes once we settle the `ftp` issue with Ovi?

**Comment by nikhartman** [comment]
Fixed, I think, in #65

**Comment by nikhartman** [comment]
Closing. Let me know if there are more problems.
